### PR TITLE
Details panel replaced by tooltip  for consistency Issue #115 

### PR DESCRIPTION
**Pull request by TimBuckers**
Details panel replaced by tooltip for consistency as mentioned in the meeting.

issue: The use of tooltips and the details panel is a bit inconsistent (why not only use one of the two?).

### CODE REVIEW

**Comment by ClintonCao** [comment]
If I zoom into a package, then the details panel still exist? (Not in the top level or in the source code level)

**Comment by TimBuckers** [comment]
You were right, but not anymore. Now it also works on lower levels.

**Comment by ClintonCao** [comment]
Nice, it is fixed.

**Comment by boninggong** [comment]
Looking good Tim, I will merge it

**Pull request merged**
